class MoreThanTwoStarsTypedefTypeSimple(Exception): ...
class BadDoubleStarsTypedefTypeSimple(Exception): ...
class BadSingleStarTypedefTypeSimple(Exception): ...
class BadTypedefTypeSimple(Exception): ...
class NotATypedef(Exception): ...
class NotATypedefEnum(Exception): ...
class BadTypedefFunction(Exception): ...