class MoreThanTwoStarsDeclarationPointerTypeSimple(Exception): ...


class BadDeclarationDoublePointerTypeSimple(Exception): ...


class BadDeclarationSinglePointerTypeSimple(Exception): ...

class BadDeclarationFixedArrayTypeSimple(Exception): ...


class BadDeclarationTypeSimple(Exception): ...


class NotATypedef(Exception): ...

class NotATypeDeclaration(Exception): ...


class BadTypedefEnum(Exception): ...


class BadTypedefEnumField(Exception): ...


class NotATypedefStruct(Exception): ...


class NotATypedefUnion(Exception): ...


class BadTypedefStruct(Exception): ...


class BadTypedefUnion(Exception): ...


class BadTypedefStructField(Exception): ...


class BadTypedefUnionField(Exception): ...


class BadDeclarationTypeFunction(Exception): ...


class NotAFunctionExport(Exception): ...


class BadFunctionExport(Exception): ...

class NotAComment(Exception): ...